[project]

name = 'info.gianlucacosta.eos.core'

version = '0.0.0'

description = 'Type-checked, dependency-free utility library for modern Python'

authors = [{ name = "Gianluca Costa", email = "gianluca@gianlucacosta.info" }]

dependencies = []

requires-python = ">=3.14, <4.0"

readme = 'README.md'

license = { text = "MIT" }

keywords = ['library', 'type-checked', 'modern', 'utilities']

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Topic :: Utilities",
]


[project.urls]

homepage = "https://github.com/giancosta86/eos-core"

repository = "https://github.com/giancosta86/eos-core"


[build-system]

requires = ["pdm-backend"]
build-backend = "pdm.backend"


[dependency-groups]

dev = [
  "ruff ~= 0.16.4",
  "pytest ~= 9.1.1",
  "pytest-cov ~= 7.1.0",
  "mypy ~= 2.3.1",
]


[tool.pdm]

distribution = true


[tool.pdm.build]

includes = ["src"]

excludes = ["src/**/*_test.py"]

source-includes = ["src/**/*_test.py"]


[tool.pdm.scripts]

clean = 'rm -rf .mypy_cache .pdm-build .pytest_cache .ruff_cache .venv dist htmlcov .coverage .pdm-python'

lint = 'ruff check src'

check-types = 'mypy src'

test = 'pytest'

verify = { composite = ['lint', 'check-types', 'test'] }
